env:
  browser: true
  node: true
  jest/globals: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
settings:
  react:
    version: "detect"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules:
  "no-void": off

  "@typescript-eslint/no-confusing-void-expression": off
  "@typescript-eslint/no-unsafe-argument": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/promise-function-async": off
  "@typescript-eslint/strict-boolean-expressions": off
  "@typescript-eslint/consistent-type-imports": off
  "@typescript-eslint/no-misused-promises": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-floating-promises": off
  "@typescript-eslint/array-type": off
  "@typescript-eslint/prefer-nullish-coalescing": off

  "react/react-in-jsx-scope": off
