FROM ubuntu

RUN apt-get update -y \
  && apt-get install -y git ffmpeg \
  && apt-get autoclean \
  && rm -rf /var/lib/apt/lists/*

COPY build/cicada-arm64 /
VOLUME [ "/data", "/config.json" ]
CMD /cicada-arm64 start -c /config.json --data /data --port 80
EXPOSE 80
