// Package apperr defines application-level error codes returned in API responses.
// Codes are strings to maintain compatibility with the TypeScript client.
package apperr

const (
	Success                                 = "success"
	ServerError                             = "server_error"
	WrongParameter                          = "wrong_parameter"
	WrongCaptcha                            = "wrong_captcha"
	NotAuthorized                           = "not_authorized"
	NotAuthorizedForAdmin                   = "not_authorized_for_admin"
	UsernameAlreadyRegistered               = "username_already_registered"
	MusicbillNotExisted                     = "musicbill_not_existed"
	MusicNotExisted                         = "music_not_existed"
	MusicAlreadyExistedInMusicbill          = "music_already_existed_in_musicbill"
	MusicNotExistedInMusicbill              = "music_not_existed_in_musicbill"
	AssetOversize                           = "asset_oversize"
	WrongAssetType                          = "wrong_asset_type"
	AssetNotExisted                         = "asset_not_existed"
	SingerNotExisted                        = "singer_not_existed"
	SingerAlreadyExisted                    = "singer_already_existed"
	SingerHasMusicCanNotBeDeleted           = "singer_has_music_can_not_be_deleted"
	NoNeedToUpdate                          = "no_need_to_update"
	AliasOverMaxLength                      = "alias_over_max_length"
	RepeatedAlias                           = "repeated_alias"
	NicknameHasUsedByOthers                 = "nickname_has_used_by_others"
	UserNotExisted                          = "user_not_existed"
	MusicForkedByOtherCanNotBeDeleted       = "music_forked_by_other_can_not_be_deleted"
	CanNotCollectMusicbillRepeatly          = "can_not_collect_musicbill_repeatly"
	MusicbillNotCollected                   = "musicbill_not_collected"
	OverUserMusicbillMaxAmount              = "over_user_musicbill_max_amount"
	CanNotDeleteAdmin                       = "can_not_delete_admin"
	CanNotResetOwnPassword                  = "can_not_reset_own_password"
	UserIsAdminAlready                      = "user_is_admin_already"
	MusicPlayRecordNotExisted               = "music_play_record_not_existed"
	CanNotInviteMusicbillOwner              = "can_not_invite_musicbill_owner"
	RepeatedSharedMusicbillInvitation       = "repeated_shared_musicbill_invitation"
	NoPermissionToDeleteMusicbillSharedUser = "no_permission_to_delete_musicbill_shared_user"
	SharedMusicbillInvitationNotExisted     = "shared_musicbill_invitation_not_existed"
	WrongUsernameOrPassword                 = "wrong_username_or_password"
	LackOf2FAToken                          = "lack_of_2fa_token"
	Wrong2FAToken                           = "wrong_2fa_token"
	TwoFAEnabledAlready                     = "two_fa_enabled_already"
	Need2FA                                 = "need_2fa"
	NoNeedTo2FA                             = "no_need_to_2fa"
	LoginTooFrequent                        = "login_too_frequent"
	LoginWith2FATooFrequent                 = "login_with_2fa_too_frequent"
	InstrumentalHasNoLyric                  = "instrumental_has_no_lyric"
	PartialUploadNotExisted                 = "partial_upload_not_existed"
	PartialUploadOwnerMismatch              = "partial_upload_owner_mismatch"
	PartialUploadRangeInvalid               = "partial_upload_range_invalid"
	PartialUploadHashMismatch               = "partial_upload_hash_mismatch"
	DiskSpaceInsufficient                   = "disk_space_insufficient"
)
