import { GLOBAL_SHORTCUT as GLOBAL_SHORTCUT_STORAGE_KEY } from './storage_key';
import { IS_MAC_OS } from '.';

export const GLOBAL_SHORTCUT = {
  TOGGLE_VISIBLE: 'toggle_visible',
  TOGGLE_PLAY: 'toggle_play',
  PREVIOUS: 'previous',
  NEXT: 'next',
};

export const GLOBAL_SHORTCUT_MAP_STORAGE_KEY = {
  [GLOBAL_SHORTCUT.TOGGLE_VISIBLE]: GLOBAL_SHORTCUT_STORAGE_KEY.TOGGLE_VISIBLE,
  [GLOBAL_SHORTCUT.TOGGLE_PLAY]: GLOBAL_SHORTCUT_STORAGE_KEY.TOGGLE_PLAY,
  [GLOBAL_SHORTCUT.PREVIOUS]: GLOBAL_SHORTCUT_STORAGE_KEY.PREVIOUS,
  [GLOBAL_SHORTCUT.NEXT]: GLOBAL_SHORTCUT_STORAGE_KEY.NEXT,
};

export const GLOBAL_SHORTCUT_MAP_LABEL = {
  [GLOBAL_SHORTCUT.TOGGLE_VISIBLE]: '显示 / 隐藏知了',
  [GLOBAL_SHORTCUT.TOGGLE_PLAY]: '播放 / 暂停',
  [GLOBAL_SHORTCUT.PREVIOUS]: '上一首',
  [GLOBAL_SHORTCUT.NEXT]: '下一首',
};

export const MUST_HAS_KEYS = IS_MAC_OS
  ? ['Command', 'Control', 'Option', 'Shift']
  : ['Ctrl', 'Alt', 'Shift'];

export const KEYBOARDJS_MAP_ELECTRON_KEY = {
  'command': IS_MAC_OS ? 'Command' : 'Super',
  'ctrl': IS_MAC_OS ? 'Control' : 'Ctrl',

  'alt': IS_MAC_OS ? 'Option' : 'Alt',
  'menu': IS_MAC_OS ? 'Option' : 'Alt',

  'one': '1',
  '1': '1',
  'two': '2',
  '2': '2',
  'three': '3',
  '3': '3',
  'four': '4',
  '4': '4',
  'five': '5',
  '5': '5',
  'six': '6',
  '6': '6',
  'seven': '7',
  '7': '7',
  'eight': '8',
  '8': '8',
  'nine': '9',
  '9': '9',
  'zero': '0',
  '0': '0',

  'graveaccent': '`',
  '`': '`',
  'dash': '-',
  '-': '-',
  'equal': '=',
  'equalsign': '=',
  '=': '=',
  'openbracket': '[',
  '[': '[',
  'closebracket': ']',
  ']': ']',
  'backslash': '\\',
  '\\': '\\',
  'semicolon': ';',
  ';': ';',
  'apostrophe': "'",
  "'": "'",
  'comma': ',',
  ',': ',',
  'period': '.',
  '.': '.',
  'slash': '/',
  'forwardslash': '/',
  '/': '/',
  'home': 'Home',
  'end': 'End',
  'pageup': 'PageUp',
  'pagedown': 'PageDown',
  'left': 'Left',
  'right': 'Right',
  'up': 'Up',
  'down': 'Down',

  'escape': 'Escape',
  'esc': 'Escape',
  'backspace': 'Backspace',
  'tab': 'Tab',
  'capslock': 'Capslock',
  'shift': 'Shift',
  'space': 'Space',
  'spacebar': 'Space',
  'enter': 'Enter',
  'insert': 'Insert',
  'ins': 'Insert',
  'delete': 'Delete',
  'del': 'Delete',

  'a': 'A',
  'b': 'B',
  'c': 'C',
  'd': 'D',
  'e': 'E',
  'f': 'F',
  'g': 'G',
  'h': 'H',
  'i': 'I',
  'j': 'J',
  'k': 'K',
  'l': 'L',
  'm': 'M',
  'n': 'N',
  'o': 'O',
  'p': 'P',
  'q': 'Q',
  'r': 'R',
  's': 'S',
  't': 'T',
  'u': 'U',
  'v': 'V',
  'w': 'W',
  'x': 'X',
  'y': 'Y',
  'z': 'Z',
};
