export const LYRIC_PANEL_CONTROLLER_GAP = 10;
export const LYRIC_PANEL_PROGRESS_BOTTOM_PADDING = 12;
export const LYRIC_PANEL_SAFE_AREA_BOTTOM = 'env(safe-area-inset-bottom, 0px)';

// 底部留白与进度条到播放按钮的视觉间距保持一致。
export const LYRIC_PANEL_BUTTON_VERTICAL_SPACE = `${
  LYRIC_PANEL_CONTROLLER_GAP + LYRIC_PANEL_PROGRESS_BOTTOM_PADDING
}px`;

export const LYRIC_PANEL_CONTROLLER_BOTTOM_PADDING = `calc(${LYRIC_PANEL_BUTTON_VERTICAL_SPACE} + ${LYRIC_PANEL_SAFE_AREA_BOTTOM})`;
