name: build and release

on:
  push:
    tags:
      - "*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/pwa/package-lock.json
      - uses: actions/setup-go@v5
        with:
          go-version-file: apps/cli/go.mod

      - run: ./build.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.tar.gz"
          token: ${{ secrets.TOKEN }}
